Skyvern-AI/skyvern-cloud:
  - source: skyvern/
    dest: skyvern/
  - source: streamlit_app/
    dest: streamlit_app/
  - source: pyproject.toml
    dest: pyproject.toml
  - source: poetry.lock
    dest: poetry.lock
  - source: setup.sh
    dest: setup.sh
  - source: .env.example
    dest: .env.example
  - source: run_ui.sh
    dest: run_ui.sh
  - source: run_skyvern.sh
    dest: run_skyvern.sh
  - source: run_alembic_check.sh
    dest: run_alembic_check.sh
  - source: skyvern-frontend/src/api/
    dest: skyvern-frontend/src/api/
  - source: skyvern-frontend/src/components/
    dest: skyvern-frontend/src/components/
  - source: skyvern-frontend/src/routes/
    dest: skyvern-frontend/src/routes/
  - source: skyvern-frontend/src/store/
    dest: skyvern-frontend/src/store/
  - source: skyvern-frontend/src/util/
    dest: skyvern-frontend/src/util/